#https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Style/DoubleNegation:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - is_
    - has_

  NamePrefixBlacklist:
    - is_
    - has_

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - config/environments/*
    - config/initializers/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - Gemfile
    - lib/templates/rails/scaffold_controller/*
    - tmp/**/*
    - vendor/**/*
    - spec/teaspoon_env.rb
    - spec/spec_helper.rb

Style/AsciiComments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Style/GuardClause:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Layout/IndentArray:
  Enabled: true
  EnforcedStyle: consistent

Layout/IndentHash:
  Enabled: true
  EnforcedStyle: consistent

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Lambda:
  Enabled: false
